package net.qipo.dao;

import java.util.List;
import net.qipo.bean.Teacher;
import org.apache.ibatis.annotations.Param;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Nov 11 19:18:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Nov 11 19:18:59 CST 2019
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Nov 11 19:18:59 CST 2019
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Nov 11 19:18:59 CST 2019
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Nov 11 19:18:59 CST 2019
     */
    int updateByPrimaryKey(Teacher record);

    void insertBatch(@Param("teachers") List<Teacher> list);

    List<Teacher> getTeachers();
}